[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear"
]

[phases.deploy]
cmds = [
  "php artisan migrate --force"
]

[start]
cmd = "frankenphp run --config /etc/caddy/Caddyfile"