[phases.build]
cmds = [
  "npm install",
  "npm run build",
  "composer install --no-dev --optimize-autoloader"
]

[phases.deploy]
cmds = [
  "php artisan migrate --force"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"